// Start an interview with the selected character
// SECURITY UPDATE: Session ID is now generated server-side using crypto.randomUUID()
async function startInterview(characterName, characterRole) {
    try {
        // Call the backend API to start the session
        // Server will generate a secure session ID
        const response = await fetch(window.API_CONFIG.ENDPOINTS.START_SESSION, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                characterName: characterName,
                characterRole: characterRole
                // sessionId is no longer sent from client - generated by server
            })
        });

        const data = await response.json();

        if (data.success) {
            console.log('Session started successfully:', data);

            // Store character information and server-provided session ID in sessionStorage
            sessionStorage.setItem('characterName', characterName);
            sessionStorage.setItem('characterRole', characterRole);
            sessionStorage.setItem('sessionId', data.sessionId); // Server-generated secure UUID

            // Store the character's greeting if available
            if (data.greeting) {
                sessionStorage.setItem('characterGreeting', data.greeting);
            }

            // Redirect to chat page
            window.location.href = 'chat.html';
        } else {
            console.error('Failed to start session:', data);
            alert('Failed to start the interview session. Please try again.');
        }

    } catch (error) {
        console.error('Error starting interview:', error);
        alert('Error connecting to server. Please make sure the backend is running.');
    }
}

// Check if a session already exists when the page loads
window.addEventListener('DOMContentLoaded', () => {
    const existingSession = sessionStorage.getItem('sessionId');

    if (existingSession && window.location.pathname.includes('index.html')) {
        // Optional: Show a warning that a session already exists
        console.log('Existing session found:', existingSession);
    }
});
